name:                haskell-monad-challenge
version:             0.1.0.0
github:              "rolandtritsch/haskell-monad-challenge"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2019 Roland Tritsch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            (Ex)Sample code for the Monad Challenges
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rolandtritsch/haskell-monad-challenge#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  example01:
    main:                Example01.hs
    source-dirs:         app
    ghc-options:
    - -main-is Example01.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monad-challenge

  example02:
    main:                Example02.hs
    source-dirs:         app
    ghc-options:
    - -main-is Example02.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monad-challenge

  example03:
    main:                Example03.hs
    source-dirs:         app
    ghc-options:
    - -main-is Example03.main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monad-challenge

tests:
  haskell-monad-challenge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monad-challenge
    - hspec