version: 2.1
jobs:
  build-haskell:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-haskell-monad-challenge-v1-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack build :haskell-monad-challenge-test
      - run:
          name: Run example01
          command: stack build :example01 --exec example01
      - run:
          name: Run example02
          command: stack build :example02 --exec example02
      - save_cache:
          name: Cache Dependencies
          key: cci-haskell-monad-challenge-v1-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - ~/.stack-work

  build-eta:
    docker:
      - image: typelead/eta:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-eta-monad-challenge-v1-{{ checksum "package.yaml" }}
      - run:
          name: Generate cabal (from package.yaml)
          command: |
            apt update &&
            apt upgrade -y &&
            apt install jq -y &&
            apt install curl -y &&
            curl -sSL https://github.com/sol/hpack/raw/master/get-hpack.sh | bash &&
            hpack --force
      - run:
          name: Init build
          command: etlas update && etlas select latest
      - run:
          name: Run build
          command: etlas build --enable-tests
      - run:
          name: Run tests
          command: export ETA_JAVA_ARGS="-Xss1024M -Xmx4096M" && etlas test
      - run:
          name: Run example01
          command: export ETA_JAVA_ARGS="-Xss1024M -Xmx4096M" && etlas run example01
      - run:
          name: Run example02
          command: export ETA_JAVA_ARGS="-Xss1024M -Xmx4096M" && etlas run example02
      - save_cache:
          name: Save Cache Dependencies
          key: cci-eta-aoc-2018-v1-{{ checksum "package.yaml" }}
          paths:
            - ~/.etlas
            - ~/.eta
            - ~/dist

workflows:
  version: 2
  full_cycle:
    jobs:
      - build-haskell
      - build-eta

general:
  branches:
    only:
      - master